export const GET_CHARACTERS = 'GET_CHARACTERS'
export const GET_CHARACTERS_QUERY = 'GET_CHARACTERS_QUERY'
export const ORDER_CHARACTERS_GENDER = 'ORDER_CHARACTERS_GENDER'
export const GET_CHARACTER_NAME = 'GET_CHARACTER_NAME'
export const GET_CHARACTER_ID = 'GET_CHARACTER_ID'
export const GET_CHARACTER_NAME_FORM = 'GET_CHARACTER_NAME_FORM'
export const POST_CHARACTER = 'POST_CHARACTER'


export const GET_EPISODES = 'GET_EPISODES'
export const GET_EPISODES_QUERY = 'GET_EPISODES_QUERY'
export const ORDER_EPISODES_SEASON = 'ORDER_EPISODES_SEASON'
export const GET_EPISODE_NAME = 'GET_EPISODE_NAME'
export const POST_EPISODE = 'POST_EPISODE'

export const GET_LOCATION = 'GET_LOCATION'
export const GET_LOCATION_QUERY = 'GET_LOCATION_QUERY'
export const ORDER_LOCATION_DIMENSION = 'ORDER_LOCATION_DIMENSION'
export const GET_LOCATION_NAME = 'GET_LOCATION_NAME'
export const POST_LOCATION = 'POST_LOCATION'

