export const GET_CHARACTERS = 'GET_CHARACTERS'
export const GET_CHARACTER_NAME = 'GET_CHARACTER_NAME'
export const GET_CHARACTER_ID = 'GET_CHARACTER_ID'

export const GET_EPISODES = 'GET_EPISODES'
export const GET_EPISODE_NAME = 'GET_EPISODE_NAME'

export const GET_LOCATION = 'GET_LOCATION'
export const GET_LOCATION_NAME = 'GET_LOCATION_NAME'

